# Generated by Django 3.1.4 on 2020-12-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_varified',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_varified',
            field=models.BooleanField(default=False),
        ),
    ]
