# Generated by Django 3.1.4 on 2020-12-29 09:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201228_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='default-profile.png', force_format=None, keep_meta=True, quality=0, size=[640, 480], upload_to='profile_pics'),
        ),
    ]
