# Generated by Django 3.1.4 on 2020-12-31 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
