# Generated by Django 3.1.4 on 2021-01-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Recruiter'), (2, 'Candidate')], default=1),
            preserve_default=False,
        ),
    ]
