# Generated by Django 3.1.4 on 2021-04-12 12:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='default-profile.png', force_format='JPEG', keep_meta=True, quality=100, size=[1920, 1080], upload_to='profile_pics'),
        ),
    ]
