# Generated by Django 3.1.4 on 2021-09-28 23:05

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210830_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='default-profile.png', force_format='JPEG', keep_meta=True, quality=100, size=[1920, 1080], upload_to=users.models.get_upload_path),
        ),
    ]
