version: "3.9"

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: tts
      POSTGRES_PASSWORD: tts
      POSTGRES_DB: tts
    networks:
      - networktts
  web:
    build:
      context: .
      dockerfile: ./compose/development/Dockerfile
    env_file:
      - ./.envs/development.env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on: [db]
    command: /start
    networks:
      - networktts

volumes:
  postgres_data:

networks:
  networktts:
    driver: bridge
