version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    env_file:
      - ./.envs/production.env
    ports:
      - 8000:8000
    command: /start
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
