version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    env_file:
      - ./.envs/production.env
    ports:
      - 8000:8000
    command: /start
  nginx-proxy:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./.envs/proxy.env  
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  acme-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.envs/proxy.env  
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme: