# Generated by Django 3.1.4 on 2021-04-29 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='note',
            name='liked_by',
            field=models.ManyToManyField(related_name='noteLikedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
